import { readFileSync } from 'node:fs'
import { describe, it, expect } from 'vitest'
import * as M from '../src/messages.js'

describe('message contract', () => {
  it('pyRepr mirrors Python !r for strings and None', () => {
    expect(M.pyRepr('store.example.com')).toBe("'store.example.com'")
    expect(M.pyRepr(null)).toBe('None')
    expect(M.pyRepr(undefined)).toBe('None')
    expect(M.pyRepr(42n)).toBe('42')
  })
  it('every vector-mandated substring is emitted by some constant/builder', () => {
    const corpus = [
      M.ERR.SIG_VERIFICATION_FAILED, M.ERR.ISSUER_MISMATCH, M.ERR.ENVELOPE_NOT_OBJECT,
      M.ERR.MISSING_PAYLOAD, M.ERR.MISSING_SIGNATURES, M.ERR.MALFORMED_SIG_BLOCK,
      M.ERR.MALFORMED_SIG_BLOCK_TYPES, M.ERR.MISSING_ISSUER_ID,
      M.noKeyInManifest('store.example.com/keys/2025-01#ed25519-9'),
      M.keyCompromised('kid'), M.keyRetired('kid'), M.duplicateKey('attest_version'),
      M.intOutOfRange(9007199254740992n), M.unknownField('promo_code'),
      M.WARN.DRM_BOUND, M.WARN.REVOCABILITY_NONE_IGNORED,
      M.COMPROMISE_WARN.RESCUE_APPLIED,
      M.COMPROMISE_WARN.CUTOFF_UNANCHORED,
      M.COMPROMISE_WARN.RESCUE_REQUIRES_ANCHORED_RECEIPT,
      M.COMPROMISE_WARN.RESCUE_RECEIPT_AFTER_CUTOFF,
      M.COMPROMISE_WARN.CUTOFF_CLAIM_IGNORED,
    ].join('')
    for (const needle of [
      'signature verification failed', 'no key', 'in issuer manifest', 'issuer_mismatch',
      'duplicate object key', 'integer out of I-JSON safe range', 'compromised',
      'drm-bound', 'unknown payload field', 'promo_code', 'retired', "revocability is 'none'",
      'compromise_rescue_applied', 'compromise_cutoff_unanchored',
      'compromise_rescue_requires_anchored_receipt', 'compromise_rescue_receipt_after_cutoff',
      'compromise_cutoff_claim_ignored',
    ]) expect(corpus.includes(needle), needle).toBe(true)
  })
})

// ---------------------------------------------------------------------------
// Trust-material messages (plan section 5.4): the parity claim, MEASURED.
//
// `trust_material.py` and `messages.ts` are required to produce byte-identical
// refusals for M1-M8. Neither language can assert that about the other, so the
// Python side — the owner of the rendering, since the messages interpolate
// `ascii()` — writes the answers once into a fixture and both suites are
// measured against it. Regenerated by hand with
// `tests/fixtures/regenerate_trust_material_messages.py`; there is no update
// flag on either side, because a test that can rewrite its own oracle records
// whatever the code does on the day it runs.
//
// Read with an absolute URL derived from this file, so the suite does not
// depend on a working directory and needs no subprocess.
// ---------------------------------------------------------------------------

interface MessageCase {
  id: string
  what?: string
  name?: string
  member?: string
  shape?: string
  reason?: string
  expected: string
}

const MESSAGE_FIXTURE = JSON.parse(
  readFileSync(new URL('../../../tests/fixtures/trust-material-messages.json', import.meta.url), 'utf8'),
) as { cases: MessageCase[] }

describe('trust-material message parity with the Python core', () => {
  const render = (c: MessageCase): string => {
    switch (c.id) {
      case 'M1':
        return M.notBytes(c.what!)
      case 'M2':
        return M.tooLarge(c.what!)
      case 'M3':
        return M.notParsed(c.what!)
      case 'M4':
        return M.notObject(c.what!)
      case 'M5':
        return M.unknownMember(c.name!)
      case 'M6':
        return M.memberShape(c.member!, c.shape!)
      case 'M7':
        return M.unparsable(c.what!, c.reason!)
      case 'M8':
        return M.notCanonical(c.what!, c.reason!)
      default:
        throw new Error(`the fixture carries an id this suite cannot render: ${c.id}`)
    }
  }

  it('every case the Python core pinned renders the same here', () => {
    const drift: string[] = []
    for (const c of MESSAGE_FIXTURE.cases) {
      const seen = render(c)
      if (seen !== c.expected) {
        drift.push(`${c.id} ${JSON.stringify(c.name ?? c.member ?? c.what)}: python ${JSON.stringify(c.expected)}, here ${JSON.stringify(seen)}`)
      }
    }
    expect(drift).toEqual([])
  })

  it('the fixture still covers all eight shared messages', () => {
    // The parity contract is a LIST, not a total: a message added to section
    // 5.4 and not to the generator would leave the two languages free to
    // disagree about it, and nothing else here would notice.
    const ids = new Set(MESSAGE_FIXTURE.cases.map((c) => c.id))
    for (const id of ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8']) {
      expect(ids.has(id), id).toBe(true)
    }
  })

  it('the corpus still reaches the rendering paths it was chosen for', () => {
    // Without this the corpus can be quietly reduced to easy names and the
    // comparison above stays green while measuring nothing.
    const names = MESSAGE_FIXTURE.cases.filter((c) => c.id === 'M5').map((c) => c.name!)
    const cps = (s: string): number[] => Array.from(s).map((ch) => ch.codePointAt(0)!)
    expect(names.some((n) => n.includes("'") && !n.includes('"')), 'no single-quote-only name').toBe(true)
    expect(names.some((n) => n.includes('"') && !n.includes("'")), 'no double-quote-only name').toBe(true)
    expect(names.some((n) => n.includes("'") && n.includes('"')), 'no name with both quotes').toBe(true)
    expect(names.some((n) => n === ''), 'no empty name').toBe(true)
    expect(names.some((n) => /[\n\r\t\\]/.test(n)), 'no escape shorthand').toBe(true)
    expect(names.some((n) => cps(n).some((c) => c < 0x20 || c === 0x7f)), 'no control character').toBe(true)
    expect(names.some((n) => cps(n).some((c) => c >= 0x80 && c <= 0xff)), 'no latin-1 range').toBe(true)
    expect(names.some((n) => cps(n).some((c) => c >= 0x100 && c <= 0xd7ff)), 'no BMP range').toBe(true)
    expect(names.some((n) => cps(n).some((c) => c > 0xffff)), 'no astral character').toBe(true)
    expect(names.some((n) => cps(n).some((c) => c >= 0xd800 && c <= 0xdfff)), 'no lone surrogate').toBe(true)
    expect(names.some((n) => n.length >= 300), 'no long name').toBe(true)
  })

  it('the two pre-rendered M3 constants are what the builder produces', () => {
    // The doors compare against `ERR.*` rather than calling the builder, so the
    // constants are a second copy of the same text and have to be pinned as
    // one: a constant that drifts from its builder is a door that refuses with
    // a message no test recognises.
    expect(M.ERR.TRUST_STORE_NOT_PARSED).toBe(M.notParsed('trust store'))
    expect(M.ERR.KEY_MANIFEST_NOT_PARSED).toBe(M.notParsed('key manifest'))
    const pinned = MESSAGE_FIXTURE.cases.filter((c) => c.id === 'M3')
    expect(pinned.map((c) => c.expected)).toContain(M.ERR.TRUST_STORE_NOT_PARSED)
    expect(pinned.map((c) => c.expected)).toContain(M.ERR.KEY_MANIFEST_NOT_PARSED)
  })

  it('the three TypeScript-only messages exist and name their subject', () => {
    // M9, M10 and M11 have no Python twin — they refuse three ways of
    // presenting bytes that only exist in JavaScript — so the fixture cannot
    // pin them and this is where they are pinned instead.
    for (const what of ['trust store', 'key manifest']) {
      for (const text of [M.notByteView(what), M.sharedMemory(what), M.detachedBuffer(what)]) {
        expect(text.startsWith(what), text).toBe(true)
      }
    }
    expect(M.notByteView('x')).toContain('Uint8Array')
    expect(M.sharedMemory('x')).toContain('shared memory')
    expect(M.detachedBuffer('x')).toContain('detached')
  })
})
