// Tests for hybrid (Ed25519 + ML-DSA-65) verification of revocation records
// and artifact manifests (v0.2 profile) — the TS sibling of
// tests/test_sibling_hybrid_sidedocs.py (Python reference, Stage 2 Task 6),
// covering every verify-behavior case that port can express.
//
// TS ships a verify-only surface for these two side-documents (no
// build_record/build_artifact_manifest analogs — see manifests.ts/
// revocation.ts module docstrings), so the two Python cases that assert
// BUILDER output shape (`*_has_both_legs`) have no TS equivalent; every
// other Python case (11 of 13) is mirrored here. Fixtures below are
// hybrid-signed directly with @noble/curves + @noble/post-quantum, the same
// convention hybrid.test.ts already established for Stage-1 hybrid receipts:
// ML-DSA-65 signing here is per-test, in-memory fixture material, never a
// committed vector, so byte-for-byte reproducibility across runs is not a
// requirement (only docs/spec/vectors/ — generated by tools/gen_vectors.py's
// deterministic oracle — needs that).
import { describe, it, expect } from 'vitest'
import { ed25519 } from '@noble/curves/ed25519'
import { ml_dsa65 } from '@noble/post-quantum/ml-dsa.js'
import { loadsStrict, canonicalBytes } from '../src/canon.js'
import type { JsonObject } from '../src/canon.js'
import { b64uEncode, b64uDecode } from '../src/b64u.js'
import { ML_DSA_65_SIG_LEN } from '../src/mldsa.js'
import { verifyArtifactManifest } from '../src/manifests.js'
import { verifyRecord, classifyRevocation } from '../src/revocation.js'
import { keyManifest as manifestHandle } from './helpers/trust.js'

const enc = (s: string) => new TextEncoder().encode(s)
const parse = (v: unknown): JsonObject => loadsStrict(enc(JSON.stringify(v))) as JsonObject

const ISSUER = 'store.example.com'
const KID = `${ISSUER}/keys/test#hybrid-1`
const VALID_FROM = '2026-01-01T00:00:00Z'
const RELEASED_AT = '2026-02-01T00:00:00Z'
const REVOKED_AT = '2026-02-01T00:00:00Z'
const RECEIPT_ID = '01ARZ3NDEKTSV4RRFFQ69G5FAV'

// TEST ONLY — fixed seeds, never use in production.
const edSeed = Uint8Array.from({ length: 32 }, () => 40)
const edPub = ed25519.getPublicKey(edSeed)
const { publicKey: mldsaPub, secretKey: mldsaSecret } = ml_dsa65.keygen(Uint8Array.from({ length: 32 }, () => 41))

function signed(body: Record<string, unknown>, sigField: string, hybrid: boolean): JsonObject {
  const bytes = canonicalBytes(parse(body))
  const sig: Record<string, unknown> = { kid: KID, sig: b64uEncode(ed25519.sign(bytes, edSeed)) }
  if (hybrid) sig['sig_ml_dsa_65'] = b64uEncode(ml_dsa65.sign(bytes, mldsaSecret))
  return parse({ ...body, [sigField]: sig })
}

function keyManifest(hybrid: boolean): JsonObject {
  const keyEntry: Record<string, unknown> = {
    kid: KID, pub: b64uEncode(edPub), valid_from: VALID_FROM, valid_to: null, status: 'active',
  }
  if (hybrid) keyEntry['pub_ml_dsa_65'] = b64uEncode(mldsaPub)
  return signed(
    { issuer: ISSUER, manifest_version: 1, issued_at: VALID_FROM, keys: [keyEntry] },
    'manifest_signature',
    hybrid,
  )
}

function record(hybrid: boolean): JsonObject {
  return signed({ receipt_id: RECEIPT_ID, status: 'revoked', revoked_at: REVOKED_AT }, 'signature', hybrid)
}

function artifacts(): Record<string, unknown>[] {
  return [{ artifact_id: 'widget-1.0.0', sha256: '0'.repeat(64) }]
}

function artifactManifest(hybrid: boolean): JsonObject {
  return signed(
    { issuer: ISSUER, series: 'widget', version: 1, released_at: RELEASED_AT, artifacts: artifacts() },
    'manifest_signature',
    hybrid,
  )
}

function flipByte(sigB64u: string): string {
  const raw = b64uDecode(sigB64u)
  raw[0] = raw[0]! ^ 0xff
  return b64uEncode(raw)
}

function withSig(doc: JsonObject, sigField: string, sig: JsonObject): JsonObject {
  return { ...doc, [sigField]: sig }
}

describe('hybrid revocation records', () => {
  it('a hybrid record verifies', () => {
    expect(verifyRecord(record(true), manifestHandle(keyManifest(true)))).toBe(true)
  })

  it('a hybrid record missing the ML-DSA-65 leg is invalid', () => {
    const doc = record(true)
    const sig = { ...(doc['signature'] as JsonObject) }
    delete sig['sig_ml_dsa_65']
    expect(verifyRecord(withSig(doc, 'signature', sig), manifestHandle(keyManifest(true)))).toBe(false)
  })

  it('a hybrid record with a tampered ML-DSA-65 leg is invalid', () => {
    const doc = record(true)
    const sig = doc['signature'] as JsonObject
    const tampered = { ...sig, sig_ml_dsa_65: flipByte(sig['sig_ml_dsa_65'] as string) }
    expect(verifyRecord(withSig(doc, 'signature', tampered), manifestHandle(keyManifest(true)))).toBe(false)
  })

  it('an Ed25519-only record against an Ed25519-only manifest is unchanged', () => {
    expect(verifyRecord(record(false), manifestHandle(keyManifest(false)))).toBe(true)
  })

  it('an Ed25519-only record with a stray ML-DSA-65 leg is invalid', () => {
    const doc = record(false)
    const sig = doc['signature'] as JsonObject
    const stray = { ...sig, sig_ml_dsa_65: b64uEncode(new Uint8Array(ML_DSA_65_SIG_LEN)) }
    expect(verifyRecord(withSig(doc, 'signature', stray), manifestHandle(keyManifest(false)))).toBe(false)
  })
})

describe('hybrid artifact manifests', () => {
  it('a hybrid manifest verifies', () => {
    expect(verifyArtifactManifest(artifactManifest(true), manifestHandle(keyManifest(true)))).toBe(true)
  })

  it('a hybrid manifest missing the ML-DSA-65 leg is invalid', () => {
    const doc = artifactManifest(true)
    const sig = { ...(doc['manifest_signature'] as JsonObject) }
    delete sig['sig_ml_dsa_65']
    expect(verifyArtifactManifest(withSig(doc, 'manifest_signature', sig), manifestHandle(keyManifest(true)))).toBe(false)
  })

  it('a hybrid manifest with a tampered ML-DSA-65 leg is invalid', () => {
    const doc = artifactManifest(true)
    const sig = doc['manifest_signature'] as JsonObject
    const tampered = { ...sig, sig_ml_dsa_65: flipByte(sig['sig_ml_dsa_65'] as string) }
    expect(verifyArtifactManifest(withSig(doc, 'manifest_signature', tampered), manifestHandle(keyManifest(true)))).toBe(false)
  })

  it('an Ed25519-only manifest against an Ed25519-only key manifest is unchanged', () => {
    expect(verifyArtifactManifest(artifactManifest(false), manifestHandle(keyManifest(false)))).toBe(true)
  })

  it('an Ed25519-only manifest with a stray ML-DSA-65 leg is invalid', () => {
    const doc = artifactManifest(false)
    const sig = doc['manifest_signature'] as JsonObject
    const stray = { ...sig, sig_ml_dsa_65: b64uEncode(new Uint8Array(ML_DSA_65_SIG_LEN)) }
    expect(verifyArtifactManifest(withSig(doc, 'manifest_signature', stray), manifestHandle(keyManifest(false)))).toBe(false)
  })
})

// §12.1 semantics through classifyRevocation: the library-level AND rule
// above is what verify.ts's classifyRevocation consumes via
// verifyRecordSignature — this pins that an unauthenticated hybrid record
// (missing the PQ leg) degrades exactly like today's unauthenticated
// Ed25519 record: ignored with the existing warning literal, never silently
// dropped and never promoted to an error. Mirrors
// test_hybrid_revocation_record_missing_mldsa_leg_ignored_with_warning_in_verify.
describe('classifyRevocation', () => {
  it('ignores an unauthenticated hybrid record with the existing warning', () => {
    const doc = record(true)
    const sig = { ...(doc['signature'] as JsonObject) }
    delete sig['sig_ml_dsa_65']
    const unauthenticated = withSig(doc, 'signature', sig)
    const payload = parse({ receipt_id: RECEIPT_ID, license: { revocability: 'policy' } })
    const warnings: string[] = []
    const errors: string[] = []

    const result = classifyRevocation(payload, [unauthenticated], keyManifest(true), warnings, errors)

    expect(result).toBe('unknown')
    expect(warnings).toEqual([`revocation record for '${RECEIPT_ID}' failed verification, ignored`])
    expect(errors).toEqual([])
  })
})
