"""Every place that declares the release version must declare the same one.

A release bump touches `pyproject.toml` and `verifiers/ts/package.json` by hand;
the two lockfiles carry the version too, and are regenerated by a separate
command (`uv lock`, `npm install`). Forgetting either leaves the repo internally
inconsistent in a way no unit test notices — but CI's `uv sync --locked` and
`npm ci` do, several minutes into a run, on a release branch. This module turns
that into a red test in one second.

These read the lockfiles as data rather than shelling out to `uv lock --check`
and `npm ci`: the point is a red line in one second inside the ordinary suite,
with no binary on PATH. CI still runs the authoritative commands, so the cost of
uv changing its lock schema is a loud error here, never a silent pass.

Real failure this catches: release 0.9.1 bumped `pyproject.toml` to 0.9.1 and
left `uv.lock` pinning the workspace root at 0.9.0, which failed both the
`python` and `supply-chain` jobs of PR #87 at `uv sync --locked`.
"""

from __future__ import annotations

import json
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def _pyproject_version() -> str:
    data = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    return str(data["project"]["version"])


def _uv_lock_version(package: str) -> str:
    """The version `uv.lock` pins for one workspace member."""
    data = tomllib.loads((REPO_ROOT / "uv.lock").read_text(encoding="utf-8"))
    for entry in data["package"]:
        if entry["name"] == package:
            return str(entry["version"])
    raise AssertionError(f"{package} is not a package in uv.lock")


def _package_json_version() -> str:
    data = json.loads((REPO_ROOT / "verifiers/ts/package.json").read_text(encoding="utf-8"))
    return str(data["version"])


def _package_lock_versions() -> list[str]:
    """Both places npm records the package's own version in its lockfile."""
    data = json.loads((REPO_ROOT / "verifiers/ts/package-lock.json").read_text(encoding="utf-8"))
    return [str(data["version"]), str(data["packages"][""]["version"])]


def _site_package_lock_version() -> str:
    """The verifier version recorded for the site's local file dependency."""
    data = json.loads((REPO_ROOT / "site/package-lock.json").read_text(encoding="utf-8"))
    return str(data["packages"]["../verifiers/ts"]["version"])


def test_uv_lock_pins_the_version_pyproject_declares() -> None:
    assert _uv_lock_version("attest-receipts") == _pyproject_version(), (
        "uv.lock is stale: run `uv lock` after bumping the version in pyproject.toml, "
        "or CI fails at `uv sync --locked`"
    )


def test_npm_lockfile_pins_the_version_package_json_declares() -> None:
    declared = _package_json_version()
    assert _package_lock_versions() == [declared, declared], (
        "verifiers/ts/package-lock.json is stale: run `npm install --package-lock-only` "
        "in verifiers/ts after bumping the version, or CI fails at `npm ci`"
    )


def test_site_lockfile_records_the_current_verifier_version() -> None:
    assert _site_package_lock_version() == _package_json_version(), (
        "site/package-lock.json has stale attest-verifier metadata: run "
        "`npm install --package-lock-only --prefix site` after bumping "
        "verifiers/ts/package.json"
    )


def test_python_and_typescript_packages_ship_the_same_version() -> None:
    assert _pyproject_version() == _package_json_version(), (
        "the two packages are released in lockstep: replace <version> with the "
        "intended release and run `uv version <version> --no-sync`, "
        "`(cd verifiers/ts && npm version <version> --no-git-tag-version)`, "
        "then `npm install --package-lock-only --prefix site`"
    )
