"""Replay every language-neutral attest conformance vector under
`docs/spec/vectors/` (design §11 Fase 1, generated by `tools/gen_vectors.py`).

These vectors ARE the conformance suite: any implementation, in any
language, is attest-conformant iff it reproduces every vector's `expected.json`
exactly. This test replays them through the Python reference `verify()` —
it is a genuine check, not a tautology, because `expected.json` was authored
by hand from design §6/§11 intent (see `tools/gen_vectors.py` docstrings and
the Task 10 report), not copied from whatever `verify()` happened to return.

Vector-directory conventions (a "vector case" is any directory containing
`expected.json`, discovered recursively so multi-part vectors like
`07-unicode-canon/a-...` and `09-commitment/b-...` work uniformly):

  - `envelope.json` (a normal JSON object) XOR `envelope.raw.json` (hand-
    written bytes fed to `verify()` untouched — vector 06's genuinely
    duplicated JSON member can never round-trip through `json.load`, which
    silently keeps only the last value for a repeated key).
  - `manifests.json`: `{"manifests": {...}, "provenance": {...}, "chains":
    {...}, "artifact_manifests": {...}, "artifact_manifest_chains": {...}}`,
    built directly into a `verify.TrustStore`. The last two (G2/G3, group 31
    only, attest-versioning.md rev 4) are keyed by `work.artifact_series`
    instead of issuer — every other leaf keeps them at the empty-object
    default, same convention as `chains`.
  - `expected.json`: `signature`, `schema`, `trust` (asserted exactly);
    `revocation`/`binding` (asserted exactly when present); `ok` (asserted
    exactly when present); `errors`/`warnings` (asserted as exact lists when
    present) and/or `errors_contains`/`warnings_contains` (each substring
    must appear in at least one entry).
  - optional `disclosure.json`: the §6 step 7 buyer-binding input, either
    `{"identifier", "identifier_type", "salt_b64u"}` (salt path) or
    `{"nonce_b64u", "sig_b64u"}` (challenge path).
  - optional `manifest_pristine.json`: present only for vector 11
    (manifest-tamper) — the untampered, self-consistent manifest, checked
    directly against the tampered copy in `manifests.json` via
    `manifests.verify_key_manifest()`.
  - optional `revocation.json` (Fase 2, vectors 15/16): a single issuer-signed
    revocation record, fed to `verify()` as `revocation_view=[record]`.
    Vectors 14/14b (Fase 2) need no new file — they populate `manifests.json`'s
    already-reserved `"chains"` member instead.
  - optional `transparency.json` / `log-keys.json` / `anchor-policy.json`
    (group 28 only, Stage 2 "transparency/corroboration layer"): fed to
    `verify()` as `transparency=`/`log_keys=`/`anchor_policy=`.
    `transparency.json` is the untrusted evidence bundle verbatim (see
    `attest.transparency.evaluate_transparency`'s evidence schema).
    `log-keys.json` is a list of `{"origin", "name", "ed25519_pub_b64u",
    "mldsa_pub_b64u"}`, each turned into a `tlog.LogKey`. `anchor-policy.json`
    is `{"pinned_headers": {<hex>: {"header_hash", "merkle_root", "time"}},
    "crqc_horizon"}`, turned into an `anchor.AnchorPolicy`. All three are
    absent (and `verify()` sees `None`) for every leaf outside group 28, so
    existing leaves see zero behavior change; `expected.json` only gains the
    `transparency`/`corroboration`/`manifest_freshness` members for group 28
    (and group 32).
  - optional `revocation-evidence.json` (group 33 only, v0.2 §8/§15
    amendment, G5/TM-47): fed to `verify()` as `revocation_evidence=`,
    reusing group 33's own `log-keys.json`/`anchor-policy.json` (same shape
    as group 28's). It is the untrusted transparency evidence bundle for the
    SPECIFIC `refund_window` revocation record in `revocation.json` — absent
    for every leaf outside group 33, so `verify()` sees `None` and existing
    leaves see zero behavior change. Group 33 leaves do NOT gain
    `transparency`/`corroboration`/`manifest_freshness` in `expected.json`
    (those stay at their zero-default `not_checked`/`none`/`not_checked`,
    unasserted): this is a DIFFERENT evidence channel from `transparency.json`.
  - optional `transfer-view.json` (group 35 only, v0.2 §17 Stage 3): a JSON
    ARRAY of untrusted claims `[{"record": <a transfer.py record>,
    "evidence": <§10.2 evidence bundle>}]`, fed to `verify()` as
    `transfer_view=`, reusing group 35's own `log-keys.json`/
    `anchor-policy.json`. Absent for every leaf outside group 35, so
    `verify()` sees `None`. Group 35 leaves do NOT gain `transparency`/
    `corroboration`/`manifest_freshness` either (same discipline as group 33).
  - optional `witness-policy.json` (group 39 only, v0.2 §11.4, P1.1b): the
    TRUSTED `attest-witness-policy-v1` DOCUMENT, fed to `verify()` as
    `witness_policy=`. It rides the same rail as `log-keys.json`/
    `anchor-policy.json` — verifier configuration, never evidence — which is
    why it is its own file and never appears nested inside
    `transparency.json`. The untrusted `transparency.json` names the epoch it
    claims (`witness_policy_epoch`); this document says whom that epoch pins.
    Absent for every leaf outside group 39, so `verify()` sees `None` there
    and `corroboration: "witnessed"` stays unreachable. Group 39 leaves carry
    `transparency`/`corroboration` in `expected.json`, same as group 28.
  - `witness-quorum.json` (group 40 only, v0.2 §11.4, P1.1b): a leaf
    containing this file is a THIRD surface, EXCLUDED from the `verify()`
    parametrization and from the chain-audit one, and driven instead by
    `test_witness_quorum_vectors`, which calls
    `witness.evaluate_activation_witness_quorum`. The file carries the call's
    own inputs: `expected_origin`/`conflict_domain` (TRUSTED call
    configuration, which raises when malformed) and `epoch_id`/`checkpoint`/
    `anchor_evidence` (UNTRUSTED, which may only degrade the verdict). The two
    trusted POLICIES stay in their own files, `witness-policy.json` and
    `anchor-policy.json`. There is no receipt in this group at all, so these
    leaves ship no `payload.json`/`envelope.json`/`manifests.json`; their
    `expected.json` shape is `{"valid": bool, "witness_time": int | null,
    "counting_control_groups": [...]}`, all three matched exactly.
  - optional `grant-view.json` (group 37 only, v0.2 §18 Stage 4): the
    untrusted evidence object `{"grant", "later_grants", "declarations",
    "anchor"}`, fed to `verify()` as `grant_view=`. Its PRESENCE is the
    capability gate: a leaf shipping none hands `verify()` `None`, which
    evaluates nothing at all and leaves `grant`/`grant_trust` at their
    `not_checked` defaults — which is exactly what leaf `37s`, the v0.1
    negative control, relies on. `anchor` is ONE §11 evidence bundle, never a
    list. Group 37's `expected.json` carries `grant` and `grant_trust`, the
    only group where either appears, and carries none of Stage 2's three
    (same discipline as groups 33 and 35).
  - `redemption.json` (group 38 only, v0.2 §18.7): a leaf containing this
    file is a FOURTH surface, EXCLUDED from the other three parametrizations
    and driven by `test_redemption_vectors`, which calls
    `grant.verify_redemption`. Like group 40's leaves it has no receipt in it
    at all, so it ships no `payload.json`/`envelope.json`/`manifests.json`;
    the file carries `{"receipt_id", "audience", "nonce_b64u", "sig_b64u",
    "holder_pubkey_b64u"}` and `expected.json` is `{"verified": bool}`,
    matched exactly. There is deliberately no `errors`/`warnings` on this
    surface: §18.7 forbids a gate fronting the delivery of content from
    having an error path an attacker can tell apart from a refusal.
  - `chain.json` (group 36 only, v0.2 §17.5 chain-of-title audit): a leaf
    containing this file is a SEPARATE audit surface, EXCLUDED from the
    `verify()` parametrization above and driven instead by
    `test_chain_audit_vectors`, which calls `transfer.audit_chain` with the
    leaf's `chain.json` (`{"payloads", "transfer_view", "revocation_view"}`),
    the sole trusted manifest in `manifests.json`, and `log-keys.json`/
    `anchor-policy.json`. Its `expected.json` shape is `{"chain_valid": bool,
    "link_status": [...], "errors_contains": [...], "warnings": [...]}`,
    matched as: `chain_valid` <-> `result.valid` exact, `link_status` exact
    list, `errors_contains` substring, `warnings` exact list.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from attest import anchor, canon, grant, keys, manifests, tlog, transfer, verify, witness

VECTORS_DIR = Path(__file__).resolve().parent.parent / "docs" / "spec" / "vectors"

_LEAF_DIRS = sorted((p.parent for p in VECTORS_DIR.rglob("expected.json")), key=str)

# Group 36 (chain-of-title audit, v0.2 §17.5) leaves are a SEPARATE audit
# surface (`transfer.audit_chain`, never `verify()`) — excluded from the
# `verify()` parametrization below and driven instead by
# `test_chain_audit_vectors`.
_CHAIN_DIRS = [p for p in _LEAF_DIRS if (p / "chain.json").exists()]
_CHAIN_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _CHAIN_DIRS]

# Group 40 (activation witness quorum, v0.2 §11.4) leaves are a THIRD surface
# (`witness.evaluate_activation_witness_quorum`, never `verify()` and never
# `audit_chain`) — excluded from both parametrizations below and driven
# instead by `test_witness_quorum_vectors`.
_QUORUM_DIRS = [p for p in _LEAF_DIRS if (p / "witness-quorum.json").exists()]
_QUORUM_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _QUORUM_DIRS]

# Group 38 (redemption, v0.2 §18.7) leaves are a FOURTH surface
# (`grant.verify_redemption`): the question is whether a holder proof is good
# for THIS custodian, which involves no receipt and no grant document at all.
# Excluded from the other three parametrizations, driven by
# `test_redemption_vectors`.
_REDEMPTION_DIRS = [p for p in _LEAF_DIRS if (p / "redemption.json").exists()]
_REDEMPTION_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _REDEMPTION_DIRS]

_VECTOR_DIRS = [
    p
    for p in _LEAF_DIRS
    if p not in _CHAIN_DIRS and p not in _QUORUM_DIRS and p not in _REDEMPTION_DIRS
]
_VECTOR_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _VECTOR_DIRS]

_TAMPER_DIRS = [p for p in _VECTOR_DIRS if (p / "manifest_pristine.json").exists()]
_TAMPER_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _TAMPER_DIRS]


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _envelope_bytes(vector_dir: Path) -> bytes:
    raw_path = vector_dir / "envelope.raw.json"
    if raw_path.exists():
        return raw_path.read_bytes()
    envelope = _load_json(vector_dir / "envelope.json")
    return json.dumps(envelope).encode("utf-8")


def _trust_store(vector_dir: Path) -> verify.TrustStore:
    data = _load_json(vector_dir / "manifests.json")
    return verify.TrustStore(
        manifests=data["manifests"],
        provenance=data["provenance"],
        chains=data.get("chains", {}),
        artifact_manifests=data.get("artifact_manifests", {}),
        artifact_manifest_chains=data.get("artifact_manifest_chains", {}),
    )


def _revocation_view(vector_dir: Path) -> list[dict[str, Any]] | None:
    path = vector_dir / "revocation.json"
    if not path.exists():
        return None
    return [_load_json(path)]


def _disclosure(vector_dir: Path) -> verify.Disclosure | None:
    path = vector_dir / "disclosure.json"
    if not path.exists():
        return None
    data = _load_json(path)
    if "salt_b64u" in data:
        return verify.Disclosure(
            identifier=data["identifier"],
            identifier_type=data["identifier_type"],
            salt=keys.b64u_decode(data["salt_b64u"]),
        )
    return verify.Disclosure(
        challenge=(keys.b64u_decode(data["nonce_b64u"]), keys.b64u_decode(data["sig_b64u"]))
    )


def _log_keys(vector_dir: Path) -> list[tlog.LogKey] | None:
    path = vector_dir / "log-keys.json"
    if not path.exists():
        return None
    return [
        tlog.LogKey(
            origin=entry["origin"],
            name=entry["name"],
            ed25519_pub=keys.b64u_decode(entry["ed25519_pub_b64u"]),
            mldsa_pub=keys.b64u_decode(entry["mldsa_pub_b64u"]),
        )
        for entry in _load_json(path)
    ]


def _anchor_policy(vector_dir: Path) -> anchor.AnchorPolicy | None:
    path = vector_dir / "anchor-policy.json"
    if not path.exists():
        return None
    data = _load_json(path)
    pinned_headers = {
        header_hash: anchor.PinnedHeader(
            header_hash=header["header_hash"],
            merkle_root=header["merkle_root"],
            time=header["time"],
        )
        for header_hash, header in data["pinned_headers"].items()
    }
    return anchor.AnchorPolicy(pinned_headers=pinned_headers, crqc_horizon=data["crqc_horizon"])


def _transparency_evidence(vector_dir: Path) -> dict[str, Any] | None:
    path = vector_dir / "transparency.json"
    if not path.exists():
        return None
    return _load_json(path)  # type: ignore[no-any-return]


def _revocation_evidence(vector_dir: Path) -> dict[str, Any] | None:
    path = vector_dir / "revocation-evidence.json"
    if not path.exists():
        return None
    return _load_json(path)  # type: ignore[no-any-return]


def _transfer_view(vector_dir: Path) -> list[dict[str, Any]] | None:
    path = vector_dir / "transfer-view.json"
    if not path.exists():
        return None
    return _load_json(path)  # type: ignore[no-any-return]


def _witness_policy(vector_dir: Path) -> dict[str, Any] | None:
    path = vector_dir / "witness-policy.json"
    if not path.exists():
        return None
    return _load_json(path)  # type: ignore[no-any-return]


def _grant_view(vector_dir: Path) -> dict[str, Any] | None:
    path = vector_dir / "grant-view.json"
    if not path.exists():
        return None
    return _load_json(path)  # type: ignore[no-any-return]


@pytest.mark.parametrize("vector_dir", _VECTOR_DIRS, ids=_VECTOR_IDS)
def test_vector_matches_spec_intended_result(vector_dir: Path) -> None:
    expected = _load_json(vector_dir / "expected.json")
    envelope_bytes = _envelope_bytes(vector_dir)
    trust_store = _trust_store(vector_dir)
    disclosure = _disclosure(vector_dir)
    revocation_view = _revocation_view(vector_dir)

    result = verify.verify(
        envelope_bytes,
        trust_store,
        revocation_view=revocation_view,
        disclosure=disclosure,
        transparency=_transparency_evidence(vector_dir),
        log_keys=_log_keys(vector_dir),
        anchor_policy=_anchor_policy(vector_dir),
        revocation_evidence=_revocation_evidence(vector_dir),
        transfer_view=_transfer_view(vector_dir),
        witness_policy=_witness_policy(vector_dir),
        grant_view=_grant_view(vector_dir),
    )

    assert result.signature == expected["signature"]
    assert result.schema == expected["schema"]
    assert result.trust == expected["trust"]
    if "revocation" in expected:
        assert result.revocation == expected["revocation"]
    if "binding" in expected:
        assert result.binding == expected["binding"]
    if "transparency" in expected:
        assert result.transparency == expected["transparency"]
    if "corroboration" in expected:
        assert result.corroboration == expected["corroboration"]
    if "manifest_freshness" in expected:
        assert result.manifest_freshness == expected["manifest_freshness"]
    if "grant" in expected:
        assert result.grant == expected["grant"]
    if "grant_trust" in expected:
        assert result.grant_trust == expected["grant_trust"]
    if "ok" in expected:
        assert result.ok == expected["ok"]
    if "errors" in expected:
        assert list(result.errors) == expected["errors"]
    if "warnings" in expected:
        assert list(result.warnings) == expected["warnings"]
    for substr in expected.get("errors_contains", []):
        assert any(substr in e for e in result.errors), (
            f"expected an error containing {substr!r}, got {result.errors!r}"
        )
    for substr in expected.get("warnings_contains", []):
        assert any(substr in w for w in result.warnings), (
            f"expected a warning containing {substr!r}, got {result.warnings!r}"
        )


@pytest.mark.parametrize("vector_dir", _TAMPER_DIRS, ids=_TAMPER_IDS)
def test_manifest_tamper_breaks_self_consistency(vector_dir: Path) -> None:
    """Vector 11's second, manifest-level property: the tampered manifest fed
    to `verify()` (in `manifests.json`) no longer self-verifies, while the
    untampered original (`manifest_pristine.json`) does — the concrete
    evidence that "manifest invalid" describes a self-consistency break, not
    just its downstream effect on receipt verification (covered by the
    `signature`/`errors_contains` assertions above)."""
    pristine = _load_json(vector_dir / "manifest_pristine.json")
    trust_data = _load_json(vector_dir / "manifests.json")
    tampered = trust_data["manifests"][pristine["issuer"]]

    assert manifests.verify_key_manifest(pristine) is True
    assert manifests.verify_key_manifest(tampered) is False


def _sole_key_manifest(vector_dir: Path) -> dict[str, Any]:
    """Group 36 only: `audit_chain` takes ONE trusted `key_manifest`, not a
    full `TrustStore` — every group 36 leaf's `manifests.json` trusts
    exactly one issuer, so its sole `"manifests"` value is that manifest."""
    data = _load_json(vector_dir / "manifests.json")
    return next(iter(data["manifests"].values()))


@pytest.mark.parametrize("vector_dir", _CHAIN_DIRS, ids=_CHAIN_IDS)
def test_chain_audit_vectors(vector_dir: Path) -> None:
    """Group 36 (v0.2 §17.5, chain-of-title audit): a SEPARATE surface from
    `verify()` — see this module's docstring for the `chain.json` shape and
    match rules."""
    expected = _load_json(vector_dir / "expected.json")
    chain = _load_json(vector_dir / "chain.json")
    key_manifest = _sole_key_manifest(vector_dir)
    log_keys = _log_keys(vector_dir)
    anchor_policy = _anchor_policy(vector_dir)
    assert log_keys is not None
    assert anchor_policy is not None

    result = transfer.audit_chain(
        chain["payloads"],
        chain["transfer_view"],
        chain["revocation_view"],
        key_manifest,
        log_keys,
        anchor_policy,
    )

    assert result.valid == expected["chain_valid"]
    assert list(result.link_status) == expected["link_status"]
    for substr in expected.get("errors_contains", []):
        assert any(substr in e for e in result.errors), (
            f"expected a chain error containing {substr!r}, got {result.errors!r}"
        )
    assert list(result.warnings) == expected["warnings"]


@pytest.mark.parametrize("vector_dir", _QUORUM_DIRS, ids=_QUORUM_IDS)
def test_witness_quorum_vectors(vector_dir: Path) -> None:
    """Group 40 (v0.2 §11.4, activation-grade witness quorum): a SEPARATE
    surface from `verify()` — see this module's docstring for the
    `witness-quorum.json` shape and match rules. The witness policy is parsed
    here rather than handed over as a document, because this entry point takes
    trusted, already-parsed configuration (unlike `verify()`, which accepts
    either)."""
    expected = _load_json(vector_dir / "expected.json")
    quorum = _load_json(vector_dir / "witness-quorum.json")
    policy = witness.parse_policy(_witness_policy(vector_dir))
    anchor_policy = _anchor_policy(vector_dir)
    assert anchor_policy is not None

    result = witness.evaluate_activation_witness_quorum(
        quorum["checkpoint"],
        witness_policy=policy,
        epoch_id=quorum["epoch_id"],
        expected_origin=quorum["expected_origin"],
        anchor_evidence=quorum["anchor_evidence"],
        anchor_policy=anchor_policy,
        conflict_domain=quorum["conflict_domain"],
    )

    assert result.valid == expected["valid"]
    assert result.witness_time == expected["witness_time"]
    assert list(result.counting_control_groups) == expected["counting_control_groups"]


@pytest.mark.parametrize("vector_dir", _REDEMPTION_DIRS, ids=_REDEMPTION_IDS)
def test_redemption_vectors(vector_dir: Path) -> None:
    """Group 38 (v0.2 §18.7, the audience-bound redemption proof): a FOURTH
    surface, `grant.verify_redemption` rather than `verify()`. There is no
    receipt in the question these leaves ask — only whether this holder proof
    is good for THIS custodian — so they ship a `redemption.json`
    (`{"receipt_id", "audience", "nonce_b64u", "sig_b64u",
    "holder_pubkey_b64u"}`) and an `expected.json` of `{"verified": bool}`.

    Every negative leaf must come back `False` rather than raise: a gate that
    fronts the delivery of content must not have an error path an attacker can
    distinguish from a refusal."""
    expected = _load_json(vector_dir / "expected.json")
    data = _load_json(vector_dir / "redemption.json")

    verified = grant.verify_redemption(
        data["receipt_id"],
        data["audience"],
        keys.b64u_decode(data["nonce_b64u"]),
        keys.b64u_decode(data["sig_b64u"]),
        data["holder_pubkey_b64u"],
    )

    assert verified == expected["verified"]


def test_vectors_directory_is_nonempty() -> None:
    """Guard against a silently-empty parametrize list (e.g. a wrong
    `VECTORS_DIR` path) making the whole suite above vacuously pass."""
    # 23 Fase 1/2 leaves (01-18) + 20 regression-corpus leaves (19-25, 2026-07-13)
    # + 8 hybrid conformance leaves (26, 2026-07-17) + 1 absent-valid_to
    # parity leaf (27, 2026-07-17) + 14 transparency/corroboration conformance
    # leaves (28, 2026-07-18) + 2 normative-ceiling leaves (29, 2026-07-22) +
    # 2 mixed-keyset leaves (30, 2026-07-22) + 5 manifest-currency leaves
    # (31, 2026-07-22) + 3 anchor-profile-v2 leaves (32, 2026-07-22, G4) +
    # 4 logged-revocation leaves (33, 2026-07-23, G5/TM-47) + 11 transfer
    # leaves (35, 2026-07-23, §17 Stage 3) + 4 transfer-chain leaves (36,
    # 2026-07-23, §17.5) + 13 witness-corroboration leaves (39, 2026-08-25,
    # §10.1/§11.4) + 20 witness-quorum leaves (40, 2026-08-25, §11.4) +
    # 23 preservation-pledge leaves (37, 2026-08-26, §18) + 4 redemption
    # leaves (38, 2026-08-26, §18.7):
    # 19 a/b, 20 a-c, 21 a-g, 22 a-c, 23 a/b, 24, 25 a/b, 26 a-h, 28 a-n,
    # 29 a/c, 30 a/b, 31 a-e, 32 a-c, 33 a-d, 35 a-k, 36 a-d, 37 a-w,
    # 38 a-d, 39 a-m, 40 a-t. Counted over
    # `_LEAF_DIRS` (ALL leaves, every surface included) — `_VECTOR_DIRS`
    # alone (the `verify()`-routed subset) excludes group 36's chain-audit
    # leaves, group 40's quorum leaves and group 38's redemption leaves.
    assert len(_LEAF_DIRS) >= 157


def test_every_leaf_is_routed_to_exactly_one_surface() -> None:
    """The four surfaces partition the corpus. Without this, a leaf shipping
    two surface files would be replayed twice, and a fifth surface file nobody
    remembered to exclude would drop out of the gate silently — which is the
    failure mode that shows up as a green suite over a truncated set."""
    assert len(_VECTOR_DIRS) + len(_CHAIN_DIRS) + len(_QUORUM_DIRS) + len(_REDEMPTION_DIRS) == len(
        _LEAF_DIRS
    )


_CANONICAL_DIRS = [p for p in _VECTOR_DIRS if (p / "canonical.json").exists()]
_CANONICAL_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _CANONICAL_DIRS]


@pytest.mark.parametrize("vector_dir", _CANONICAL_DIRS, ids=_CANONICAL_IDS)
def test_payload_reserializes_to_committed_canonical_bytes(vector_dir: Path) -> None:
    """Cross-language round-trip identity, statically: the leaf ships the
    exact canonical serialization of its payload; this runner (and the TS
    conformance runner) re-serialize the parsed payload through their own
    canonical serializer and must reproduce those bytes exactly. Python
    bytes == TS bytes == committed bytes ⟹ Py→TS→Py round-trip identity
    with zero cross-runtime orchestration."""
    envelope = canon.loads_strict(_envelope_bytes(vector_dir))
    assert isinstance(envelope, dict)
    expected_bytes = (vector_dir / "canonical.json").read_bytes()
    assert canon.canonical_bytes(envelope["payload"]) == expected_bytes
