"""The refusal messages of the trust-material boundary, pinned as data (front F6, T1).

WHAT THIS FILE MEASURES, AND WHY IT IS NOT A UNIT TEST
------------------------------------------------------
`trust_material.py` and `verifiers/ts/src/messages.ts` are required to produce
BYTE-IDENTICAL refusals for M1-M8 (plan section 5.4). Two modules in two
languages cannot assert that about each other: each one can only assert what it
believes. So the claim is turned into an artefact both sides can be measured
against -- `tests/fixtures/trust-material-messages.json`, generated once by the
Python side, which owns the rendering.

This file answers ONE question: is that artefact still what the Python
constants say? The TypeScript twin (`verifiers/ts/test/messages.test.ts`) reads
the same bytes and answers the mirror question for `messages.ts`. Neither test
can pass by agreeing with itself, because neither one writes the file: the
fixture is regenerated by hand with
`tests/fixtures/regenerate_trust_material_messages.py`, and there is
deliberately NO update flag here. A test that can rewrite its own oracle
records whatever the code does; this one can only disagree with it.

Both sides therefore drift loudly: a change to a `_MSG_*` template turns this
file red until someone regenerates, and a regeneration turns the TypeScript
file red until someone matches it there. That is the whole mechanism.

WHAT IT DOES NOT MEASURE
------------------------
That the messages are RAISED where the grammar says they are: that is
`tests/test_trust_material_parse.py`, which drives the boundary with real
documents. Here the templates are rendered directly, so a message that is
correct and unreachable still passes -- and a message that is reachable and
wrong still fails, which is the half this file owns.
"""

from __future__ import annotations

import json
from typing import Any

import pytest

from attest import canon, trust_material
from tests.fixtures.regenerate_trust_material_messages import (
    FIXTURE_PATH,
    derive_cases,
    derive_unknown_member_choices,
)


def _load_fixture() -> dict[str, Any]:
    """The pinned fixture, read as bytes and parsed with the stdlib.

    `json` and not `canon`: the fixture is an ordinary test artefact, and using
    the library's own parser to read the file that pins the library's own
    messages would make one defect able to hide another.
    """
    raw = FIXTURE_PATH.read_bytes()
    parsed: dict[str, Any] = json.loads(raw)
    return parsed


def test_fixture_exists_and_is_a_case_list() -> None:
    """The pin exists on disk and has the shape both languages read.

    Stated as its own test because every assertion below depends on it: when
    the fixture is missing or malformed, one failure that names the file is a
    better report than fifty that name individual cases.
    """
    assert FIXTURE_PATH.exists(), (
        f"missing {FIXTURE_PATH}; regenerate it with "
        "`uv run python tests/fixtures/regenerate_trust_material_messages.py`"
    )
    fixture = _load_fixture()
    assert isinstance(fixture, dict)
    cases = fixture["cases"]
    assert isinstance(cases, list)
    assert cases, "the fixture pins nothing"
    for case in cases:
        assert isinstance(case, dict)
        assert isinstance(case["id"], str)
        assert isinstance(case["expected"], str)


def test_every_pinned_case_still_renders_from_the_module_constants() -> None:
    """The fixture is what `trust_material`'s own templates produce, case by case.

    Compared case by case rather than list against list: a whole-list assertion
    on fifty-odd entries reports "these two lists differ" and leaves whoever
    reads it to diff them by eye. The failure has to name the case, because the
    case is what somebody has to go and fix.
    """
    fixture = _load_fixture()
    pinned: list[dict[str, Any]] = fixture["cases"]
    derived = derive_cases()

    pinned_keys = [_case_key(case) for case in pinned]
    derived_keys = [_case_key(case) for case in derived]
    assert pinned_keys == derived_keys, (
        "the pinned fixture covers different cases than the generator derives; "
        "regenerate it with "
        "`uv run python tests/fixtures/regenerate_trust_material_messages.py`"
    )

    for pinned_case, derived_case in zip(pinned, derived, strict=True):
        assert pinned_case == derived_case, (
            f"case {_case_key(pinned_case)} drifted: the fixture pins "
            f"{pinned_case['expected']!r} and the module now renders "
            f"{derived_case['expected']!r}"
        )


def _case_key(case: dict[str, Any]) -> tuple[str, ...]:
    """A case's identity: its message id plus whatever slots it fills.

    Derived from the case itself instead of a hand-written list of key names,
    so a case shape added to the generator is compared rather than silently
    ignored -- the failure mode a hand-written list has by construction.
    """
    return (
        case["id"],
        *(f"{name}={case[name]!r}" for name in sorted(case) if name not in ("id", "expected")),
    )


def test_the_corpus_reaches_the_renderer_paths_it_was_chosen_for() -> None:
    """The names in the corpus still exercise the cases they were picked for.

    Without this, the corpus can be quietly reduced to easy names and the
    fixture stays green while measuring nothing. Each condition below is a
    rendering path that has diverged between the two languages before, or that
    a careless reimplementation would get wrong: quote selection, escapes,
    non-ASCII, astral, and a lone surrogate.
    """
    derived = derive_cases()
    names = [case["name"] for case in derived if case["id"] == "M5"]

    assert any("'" in name and '"' not in name for name in names), "no single-quote-only name"
    assert any('"' in name and "'" not in name for name in names), "no double-quote-only name"
    assert any("'" in name and '"' in name for name in names), "no name with both quotes"
    assert any(name == "" for name in names), "no empty name"
    assert any("\n" in name for name in names), "no newline"
    assert any("\t" in name for name in names), "no tab"
    assert any("\\" in name for name in names), "no backslash"
    assert any(any(ord(ch) < 0x20 or ord(ch) == 0x7F for ch in name) for name in names), (
        "no control character"
    )
    assert any(any(0x80 <= ord(ch) <= 0xFF for ch in name) for name in names), "no latin-1 range"
    assert any(any(0x100 <= ord(ch) <= 0xFFFF for ch in name) for name in names), "no BMP range"
    assert any(any(ord(ch) > 0xFFFF for ch in name) for name in names), "no astral character"
    assert any(any(0xD800 <= ord(ch) <= 0xDFFF for ch in name) for name in names), (
        "no lone surrogate"
    )
    assert any(len(name) >= 300 for name in names), "no long name"


@pytest.mark.parametrize("identifier", ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8"])
def test_every_message_of_section_5_4_is_pinned(identifier: str) -> None:
    """All eight Python-side message ids appear in the fixture.

    The parity contract is a list, not a total: a message added to section 5.4
    and not to the generator would leave the two languages free to disagree
    about it, and nothing else here would notice.
    """
    fixture = _load_fixture()
    ids = {case["id"] for case in fixture["cases"]}
    assert identifier in ids


def test_the_pinned_unknown_member_choices_are_what_the_boundary_still_does() -> None:
    """Each pinned document is still refused with the pinned message.

    This half of the fixture pins a CHOICE, not a rendering: which of several
    unknown members the refusal names. Section 5.3 names the minimum in
    canonical key order, and the TypeScript suite asserts its own boundary
    produces the same string from the same bytes -- so a core that started
    choosing differently is red on one side or the other, never silent on both.
    """
    fixture = _load_fixture()
    pinned: list[dict[str, Any]] = fixture["unknown_member_choice"]
    assert pinned, "the fixture pins no choice at all"
    assert [c["document"] for c in pinned] == [
        c["document"] for c in derive_unknown_member_choices()
    ], "the pinned documents are not the ones the generator derives; regenerate the fixture"
    for case in pinned:
        with pytest.raises(trust_material.TrustMaterialError) as caught:
            trust_material.TrustStore.from_bytes(case["document"].encode())
        assert str(caught.value) == case["expected"], case["document"]
        assert caught.value.member is None


def test_the_pinned_documents_can_tell_the_new_rule_from_the_old_one() -> None:
    """Non-vacuity: every pinned document disagrees with document order.

    A document whose first member already IS the canonical minimum cannot
    separate "first in the document" from "first in canonical order", so it
    would pin nothing. At least one must also separate UTF-16 CODE UNIT order
    from CODE POINT order, which is what makes this a test of JCS rather than
    of the word "sorted": an astral character encodes to a surrogate pair
    starting at U+D800, so it sorts BELOW U+FB00 by code unit and ABOVE it by
    code point.
    """
    known = set(trust_material._MEMBER_SHAPES)
    code_point_discriminates = 0
    for case in _load_fixture()["unknown_member_choice"]:
        parsed = json.loads(case["document"])
        unknown = [name for name in parsed if name not in known]
        if len(unknown) < 2:
            continue
        by_code_unit = min(unknown, key=canon.canonical_key_order)
        by_code_point = min(unknown)
        assert unknown[0] != by_code_unit, f"{case['document']} agrees with document order"
        if by_code_point != by_code_unit:
            code_point_discriminates += 1
    assert code_point_discriminates > 0, (
        "no pinned document separates UTF-16 code-unit order from code-point order"
    )
