"""Property tests over MUTATED key manifests (v0.1 §7.1).

The group-41 conformance vectors are a CLOSED list of hand-picked examples,
and an adversarial pass just found six defects none of them covered. An
example list shares the blind spots of whoever wrote it. These tests defend
the PROPERTIES those examples were only ever samples of, over mutations
generated by `tests.strategies.malformed_manifests`:

P1  absorbing floor   — any `keys[]` entry marking a kid compromised must
                        forbid a `signature: "valid"` verdict for that kid.
P2  no crash          — malformed manifest data reaches every entry point as
                        a rejection, never as an unhandled exception.
P3  no resurrection   — a successor listing a compromised kid as anything
                        else is never accepted, by either gate.
P4  active signer      — continuity may use the first signer entry for key
                        material, but signer status must observe every duplicate.
"""

from __future__ import annotations

import json
from typing import Any

import pytest
from hypothesis import HealthCheck, example, given, settings
from hypothesis import strategies as st

from attest import issue, keys, manifests, verify
from tests.helpers import make_payload
from tests.strategies import malformed_manifests as malformed

ISSUER = "store.example.com"
KID = f"{ISSUER}/keys/mutation#ed25519-1"
DECLARER_KID = f"{ISSUER}/keys/mutation#ed25519-2"

# Fixed test-only seeds.
KP = keys.from_seed(bytes([81]) * 32)
DECLARER_KP = keys.from_seed(bytes([82]) * 32)

VALID_FROM = "2026-01-01T00:00:00Z"
SUCCESSOR_ISSUED_AT = "2026-08-01T00:00:00Z"

# Ed25519 signing dominates the cost of every example, so the budget stays
# small (this suite runs in CI on every push) and the deadline is off: a
# per-example wall-clock deadline over a signature-heavy body only ever
# produces flakes, never information.
PROPERTY_SETTINGS = settings(
    max_examples=30,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow],
)

# The ONLY exceptions `verify.verify` declares (see its caller-contract block):
# a wrong CONTAINER for one of the four evidence-view arguments. Hostile
# CONTENT inside a well-shaped view — which is all these tests ever supply —
# is documented never to raise, so a TypeError carrying any other message is
# the defect P2 exists to catch, not a contract-sanctioned refusal.
VERIFY_DECLARED_TYPE_ERRORS = frozenset(
    {
        "revocation_view must be a list of records or None",
        "transfer_view must be a list of claims or None",
        "compromise_view must be a list of claims or None",
        "grant_view must be an evidence object or None",
    }
)

# `manifests.py`'s fail-closed guards raise `ValueError`, but only on the WRITE
# path (`build_key_manifest`/`rotate_key_manifest`), which P3 exercises. The
# read-only entry points P2 drives — `find_key`, `verify_key_manifest`,
# `check_continuity` — all document "never raises"/"fails closed", so P2
# admits nothing at all from them.
MANIFESTS_DECLARED_EXCEPTIONS: tuple[type[Exception], ...] = (ValueError,)


def _wire(envelope: dict[str, Any]) -> bytes:
    return json.dumps(envelope).encode("utf-8")


def _entry(kid: str, kp: keys.SigningKeyPair, status: str = "active") -> dict[str, Any]:
    return manifests.key_entry(kid, kp.pub, VALID_FROM, None, status)


def _manifest(entries: list[dict[str, Any]], version: object = 1) -> dict[str, Any]:
    """Sign a manifest WITHOUT the public builder.

    These are hostile or already-published views, not issuance: since the
    v0.1 §7.1 amendment (2026-08-26) `build_key_manifest` refuses to sign a
    duplicated `kid`, which is exactly the shape the verifier side must still
    be tested against. The body and signature are byte-identical to what the
    builder produces for every manifest the builder still accepts.
    """
    body: dict[str, Any] = {
        "issuer": ISSUER,
        "manifest_version": version,
        "issued_at": VALID_FROM,
        "keys": entries,
    }
    body["manifest_signature"] = manifests.sign_signature_block(
        manifests._signable(body),  # type: ignore[attr-defined]
        DECLARER_KP,
        DECLARER_KID,
    )
    return body


def _trust(manifest: dict[str, Any]) -> verify.TrustStore:
    return verify.TrustStore(manifests={ISSUER: manifest}, provenance={ISSUER: "tls"}, chains={})


# One well-formed §7.1 manifest and one receipt signed by KID, built once:
# every mutation below is a hostile edit of this manifest, and every example
# re-uses the same receipt bytes.
WELL_FORMED = _manifest([_entry(KID, KP), _entry(DECLARER_KID, DECLARER_KP)])
RECEIPT_BYTES = _wire(issue.issue(make_payload(), KP, KID))

COMPROMISED_ENTRIES = [_entry(KID, KP, "compromised"), _entry(DECLARER_KID, DECLARER_KP)]
COMPROMISED_PREDECESSOR = _manifest(COMPROMISED_ENTRIES)

# The shape of the known duplicate-kid defect, pinned as an explicit example so
# P1's xfail is deterministic instead of depending on the draw: `find_key`
# returns the FIRST entry, which is active, while the second, equally signed
# entry says the same kid is compromised.
KNOWN_DUPLICATE_KID_DEFECT = _manifest(
    [
        _entry(KID, KP, "active"),
        _entry(KID, KP, "compromised"),
        _entry(DECLARER_KID, DECLARER_KP),
    ]
)


# --- P1: the compromise floor is absorbing ----------------------------------


@PROPERTY_SETTINGS
@given(manifest=malformed.manifests_marking_kid_compromised(WELL_FORMED, KID))
@example(manifest=KNOWN_DUPLICATE_KID_DEFECT)
def test_p1_any_entry_marking_the_kid_compromised_forbids_a_valid_signature(
    manifest: dict[str, Any],
) -> None:
    """v0.1 §7.3: *any* held entry marking K compromised must win.

    Which entry an implementation happens to read first is an implementation
    detail; the evidence the verifier holds is the whole array.
    """
    result = verify.verify(RECEIPT_BYTES, _trust(manifest))

    assert result.signature != "valid"


# --- P2: malformed input is refused, never crashed on -----------------------


@PROPERTY_SETTINGS
@given(manifest=malformed.malformed_manifests(WELL_FORMED))
def test_p2_malformed_manifests_never_raise_out_of_the_entry_points(
    manifest: dict[str, Any],
) -> None:
    """A refusal is a valid outcome; an exception reaching the caller is not.

    Manifests arrive from untrusted sources, so every entry point that touches
    one must fail closed rather than propagate a `KeyError`/`TypeError`/
    `AttributeError` out of the library.
    """
    # Channel 1: the mutated manifest IS the trust-store manifest.
    try:
        verify.verify(RECEIPT_BYTES, _trust(manifest))
    except TypeError as exc:
        assert str(exc) in VERIFY_DECLARED_TYPE_ERRORS, (
            f"verify() raised an undeclared TypeError on a mutated manifest: {exc}"
        )

    # Channel 2: the trust store is clean and the mutation arrives as an
    # untrusted §19 compromise claim.
    try:
        verify.verify(
            RECEIPT_BYTES,
            _trust(WELL_FORMED),
            compromise_view=[{"manifest": manifest}],
        )
    except TypeError as exc:
        assert str(exc) in VERIFY_DECLARED_TYPE_ERRORS, (
            f"verify() raised an undeclared TypeError on a mutated claim: {exc}"
        )

    # The three read-only `manifests` entry points declare no exception at all:
    # anything escaping these four calls fails the test by propagating.
    manifests.find_key(manifest, KID)
    manifests.verify_key_manifest(manifest)
    manifests.check_continuity(WELL_FORMED, manifest)
    manifests.check_continuity(manifest, WELL_FORMED)


# --- P3: a compromised kid is never resurrected -----------------------------


@PROPERTY_SETTINGS
@given(entries=malformed.entries_resurrecting_kid(COMPROMISED_ENTRIES, KID))
def test_p3_successor_can_never_resurrect_a_compromised_kid(
    entries: list[dict[str, Any]],
) -> None:
    """v0.1 §7.3: there is no un-compromise ceremony.

    Both gates must refuse: the builder that is handed the predecessor, and
    the continuity predicate that is handed two published manifests. A signed
    successor is still a successor — the signature authenticates the bytes,
    it does not license the state change inside them.
    """
    with pytest.raises(MANIFESTS_DECLARED_EXCEPTIONS):
        manifests.build_key_manifest(
            ISSUER,
            2,
            SUCCESSOR_ISSUED_AT,
            entries,
            DECLARER_KP,
            DECLARER_KID,
            previous=COMPROMISED_PREDECESSOR,
        )

    # Same ambiguity, published rather than built: sign it properly, so the
    # only thing continuity can object to is the resurrection itself.
    successor = _manifest(entries, version=2)
    successor["issued_at"] = SUCCESSOR_ISSUED_AT
    successor["manifest_signature"] = manifests.sign_signature_block(
        manifests._signable(successor),  # type: ignore[attr-defined]
        DECLARER_KP,
        DECLARER_KID,
    )

    assert manifests.check_continuity(COMPROMISED_PREDECESSOR, successor) is False


@PROPERTY_SETTINGS
@given(
    active_before=st.integers(min_value=1, max_value=3),
    active_after=st.integers(min_value=0, max_value=3),
)
@example(active_before=1, active_after=0)
def test_p4_continuity_signer_status_reads_every_duplicate_entry(
    active_before: int, active_after: int
) -> None:
    signer_entries = [_entry(DECLARER_KID, DECLARER_KP, "active") for _ in range(active_before)]
    signer_entries.append(_entry(DECLARER_KID, DECLARER_KP, "compromised"))
    signer_entries.extend(_entry(DECLARER_KID, DECLARER_KP, "active") for _ in range(active_after))
    predecessor = _manifest([_entry(KID, KP), *signer_entries])
    successor = _manifest(
        [_entry(KID, KP), _entry(DECLARER_KID, DECLARER_KP, "compromised")], version=2
    )
    successor["issued_at"] = SUCCESSOR_ISSUED_AT
    successor["manifest_signature"] = manifests.sign_signature_block(
        manifests._signable(successor),
        DECLARER_KP,
        DECLARER_KID,  # type: ignore[attr-defined]
    )

    # Since the v0.1 §7.1 amendment (2026-08-26) the ambiguous predecessor is
    # refused by self-consistency itself, one layer above continuity. That
    # would make the property below vacuous through `check_continuity` alone,
    # so the signer-status predicate is asserted directly: a regression from
    # reading EVERY entry back to a first-match read stays detectable.
    assert manifests.verify_key_manifest(predecessor) is False
    assert manifests.verify_key_manifest(successor) is True
    assert manifests._kid_is_active_for_continuity(predecessor, DECLARER_KID) is False  # type: ignore[attr-defined]
    assert manifests.check_continuity(predecessor, successor) is False
