"""Property tests for `attest.views` (plan A11, T3.4).

An example list shares the blind spots of whoever wrote it, so the not-well-
formed coverage here is generated by MUTATION of a well-formed artifact — the
same model `tests/strategies/malformed_manifests.py` already established for
key manifests, reused rather than re-invented, and extended to the three
documents this module builds.

Three properties are asserted across every generated input:

- nothing but `ViewError` ever escapes a builder;
- a mutation that changes an artifact's canonical bytes is REFUSED, never
  silently repaired, truncated or partially accepted;
- a hostile subclass of `dict`/`list`/`str`/`int` never reaches
  canonicalization and never changes the artifact produced.
"""

from __future__ import annotations

import copy
import hashlib
import json
from pathlib import Path
from typing import Any

import pytest
from hypothesis import HealthCheck, assume, given, settings
from hypothesis import strategies as st

from attest import canon, keys, manifests, revocation, transfer, verify, views
from tests.strategies import malformed_manifests as malformed

VECTORS = Path(__file__).resolve().parents[1] / "docs" / "spec" / "vectors"

PROPERTY_SETTINGS = settings(
    max_examples=30,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow],
)


def _json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


CLAIM: dict[str, Any] = _json(
    VECTORS / "41-compromise-cutoff" / "a-rescued-anchored-before-cutoff" / "compromise-view.json"
)[0]
MANIFEST: dict[str, Any] = CLAIM["manifest"]
EVIDENCE: dict[str, Any] = CLAIM["evidence"]
TRANSFER_CLAIM: dict[str, Any] = _json(
    VECTORS / "35-transfer" / "a-transferred-with-backing" / "transfer-view.json"
)[0]
TRANSFER_RECORD: dict[str, Any] = TRANSFER_CLAIM["record"]
TRANSFER_EVIDENCE: dict[str, Any] = TRANSFER_CLAIM["evidence"]
REVOCATION_RECORD: dict[str, Any] = _json(VECTORS / "15-revoked-policy" / "revocation.json")


# --- the manifest mutations, reusing the repo's own strategies ---------------


@PROPERTY_SETTINGS
@given(malformed.malformed_manifests(MANIFEST))
def test_a_mutated_declaration_manifest_is_refused_or_rebuilds_identically(
    mutated: dict[str, Any],
) -> None:
    """Either `ViewError`, or the mutation was canonically a no-op and the
    claim comes back byte-identical. There is no third outcome: a manifest
    that changed at all changes its own `manifest_sha256`, and the evidence
    then commits to a document that no longer exists."""
    try:
        built = views.build_compromise_claim(mutated, copy.deepcopy(EVIDENCE))
    except views.ViewError:
        return
    assert canon.canonical_bytes(built) == canon.canonical_bytes(CLAIM)


@PROPERTY_SETTINGS
@given(malformed.manifests_marking_kid_compromised(MANIFEST, MANIFEST["keys"][0]["kid"]))
def test_a_declaration_that_still_marks_the_kid_is_still_judged_on_its_form(
    mutated: dict[str, Any],
) -> None:
    """Marking a kid `compromised` is necessary, never sufficient: these
    mutations all keep the declaration meaningful and must still be refused on
    form, signature or evidence commitment."""
    try:
        built = views.build_compromise_claim(mutated, copy.deepcopy(EVIDENCE))
    except views.ViewError:
        return
    assert canon.canonical_bytes(built) == canon.canonical_bytes(CLAIM)


# --- evidence mutations ------------------------------------------------------


def _differs(mutated: object, original: object) -> bool:
    """Did the mutation change the artifact at all?

    A generated "mutation" that happens to reproduce the original is not a
    hostile input, and asserting that it is refused asserts a falsehood. Every
    refusal property below is guarded by this, so a pool that goes stale
    against a new vector shows up as fewer examples, never as a false green.
    """
    try:
        return canon.canonical_bytes(mutated) != canon.canonical_bytes(original)
    except Exception:
        return True


EVIDENCE_MEMBERS: tuple[str, ...] = (
    "entry",
    "leaf_index",
    "tree_size",
    "inclusion_proof",
    "checkpoint",
)


def _hostile_values(evidence: dict[str, Any]) -> dict[str, tuple[object, ...]]:
    """One hostile pool per member, RELATIVE to the evidence being mutated.

    The index pair is why this is a function and not a constant. `tree_size: 1`
    is hostile for evidence whose `leaf_index` is 1 and is the CORRECT value for
    evidence whose `leaf_index` is 0 — a fixed pool written against one vector
    quietly becomes a no-op against another, and a no-op "mutation" asserted to
    be refused is a test asserting a falsehood. Measured: it happened here, on
    the 35a transfer evidence, and only a mutation run surfaced it.
    """
    leaf_index = evidence["leaf_index"]
    tree_size = evidence["tree_size"]
    return {
        "entry": (None, True, 0, "key-manifest", [], {}, {"type": "key-manifest"}),
        "leaf_index": (None, True, -1, "1", [], {}, tree_size, tree_size + 5),
        "tree_size": (None, True, -3, "2", [], {}, leaf_index, leaf_index - 1),
        "inclusion_proof": (
            None,
            True,
            0,
            "ab",
            {},
            [None],
            [""],
            ["zz" * 32],
            ["AB" * 32],
            ["ab" * 32 + "a"],
            ["ab" * 31],
            ["ab" * 32] * (views.MAX_INCLUSION_PROOF_NODES + 1),
        ),
        "checkpoint": (None, True, 0, [], {}),
        "anchors": (None, True, 0, "anchors", []),
    }


@st.composite
def hostile_evidence(draw: st.DrawFn, evidence: dict[str, Any]) -> dict[str, Any]:
    """One evidence member removed, retyped or added — one class per draw."""
    hostile = _hostile_values(evidence)
    mutated = copy.deepcopy(evidence)
    shape = draw(st.sampled_from(("remove", "retype", "extra", "entry")))
    if shape == "remove":
        del mutated[draw(st.sampled_from(EVIDENCE_MEMBERS))]
    elif shape == "retype":
        member = draw(st.sampled_from((*EVIDENCE_MEMBERS, "anchors")))
        mutated[member] = draw(st.sampled_from(hostile[member]))
    elif shape == "extra":
        mutated[draw(st.sampled_from(("proof", "__proto__", "type", "record_sha256")))] = draw(
            st.sampled_from((1, "x", None, {}))
        )
    else:
        entry = dict(mutated["entry"])
        # The entry's members depend on the rail (a `key-manifest` entry carries
        # `manifest_version`, a `transfer-record` entry carries `record_sha256`),
        # so they come from the artifact rather than from a hardcoded list.
        member = draw(st.sampled_from(sorted(entry)))
        if draw(st.booleans()):
            del entry[member]
        else:
            entry[member] = draw(st.sampled_from((None, True, 0, "x", [], {})))
        mutated["entry"] = entry
    return mutated


@PROPERTY_SETTINGS
@given(hostile_evidence(EVIDENCE))
def test_hostile_evidence_is_always_refused(mutated: dict[str, Any]) -> None:
    assume(_differs(mutated, EVIDENCE))
    with pytest.raises(views.ViewError):
        views.build_compromise_claim(copy.deepcopy(MANIFEST), mutated)


@PROPERTY_SETTINGS
@given(st.permutations(sorted(EVIDENCE["entry"])))
def test_permuting_the_entry_members_changes_nothing(order: list[str]) -> None:
    """`entry` is compared as an OBJECT, so member order is not information —
    the claim built from a permuted entry is byte-identical."""
    evidence = copy.deepcopy(EVIDENCE)
    evidence["entry"] = {member: EVIDENCE["entry"][member] for member in order}
    built = views.build_compromise_claim(copy.deepcopy(MANIFEST), evidence)
    assert canon.canonical_bytes(built) == canon.canonical_bytes(CLAIM)


def test_an_empty_inclusion_proof_is_a_shape_the_builder_admits() -> None:
    """A one-leaf tree has an empty proof (vector 35a carries one). The builder
    checks SHAPE; whether the proof actually reconstructs the root is the
    verifier's question, against its own pins."""
    evidence = copy.deepcopy(EVIDENCE)
    evidence["inclusion_proof"] = []
    claim = views.build_compromise_claim(copy.deepcopy(MANIFEST), evidence)
    assert claim["evidence"]["inclusion_proof"] == []


# --- transfer record mutations -----------------------------------------------

TRANSFER_HOSTILE: dict[str, tuple[object, ...]] = {
    "receipt_id": (None, True, 0, "", "not-a-ulid", "01JZ5PDHT0000G40R40M30E20", [], {}),
    "new_receipt_id": (None, True, 0, "", "01jz5pdht040g2081040g20810", [], {}),
    "new_holder_pubkey": (None, True, 0, "", "!" * 43, "A" * 42, "A" * 44, [], {}),
    "transferred_at": (None, True, 0, "", "2025-7-20T0:0:0Z", "2025-07-20", [], {}),
    "holder_authorization": (None, True, 0, "", [], {}, {"sig": "short"}, {"sig": None}),
    "signature": (None, True, 0, "", [], {}, {"kid": "store.example.com/k#1"}),
}


@st.composite
def hostile_transfer_record(draw: st.DrawFn, record: dict[str, Any]) -> dict[str, Any]:
    mutated = copy.deepcopy(record)
    member = draw(st.sampled_from(views._TRANSFER_RECORD_MEMBERS))
    shape = draw(st.sampled_from(("remove", "retype", "extra")))
    if shape == "remove":
        del mutated[member]
    elif shape == "retype":
        mutated[member] = draw(st.sampled_from(TRANSFER_HOSTILE[member]))
    else:
        mutated[draw(st.sampled_from(("memo", "__proto__", "reason")))] = "x"
    return mutated


@PROPERTY_SETTINGS
@given(hostile_transfer_record(TRANSFER_RECORD))
def test_every_transfer_record_member_is_load_bearing(mutated: dict[str, Any]) -> None:
    """All six members are covered by `record_sha256`, so no mutation of any of
    them can survive the evidence commitment even when its SHAPE is legal."""
    assume(_differs(mutated, TRANSFER_RECORD))
    with pytest.raises(views.ViewError):
        views.build_transfer_claim(mutated, copy.deepcopy(TRANSFER_EVIDENCE))


@PROPERTY_SETTINGS
@given(hostile_evidence(TRANSFER_EVIDENCE))
def test_hostile_transfer_evidence_is_always_refused(mutated: dict[str, Any]) -> None:
    assume(_differs(mutated, TRANSFER_EVIDENCE))
    with pytest.raises(views.ViewError):
        views.build_transfer_claim(copy.deepcopy(TRANSFER_RECORD), mutated)


# --- revocation record mutations ---------------------------------------------

REVOCATION_HOSTILE: dict[str, tuple[object, ...]] = {
    "receipt_id": (None, True, 0, "", "not-a-ulid", [], {}),
    "status": (None, True, 0, "", "revoke", "REVOKED", "expired", [], {}),
    "revoked_at": (None, True, 0, "", "2025-8-1T0:0:0Z", "2025-08-01", [], {}),
    "signature": (None, True, 0, "", [], {}, {"sig": "x"}, {"kid": 1, "sig": "x"}),
}


@st.composite
def hostile_revocation_record(draw: st.DrawFn, record: dict[str, Any]) -> dict[str, Any]:
    mutated = copy.deepcopy(record)
    member = draw(st.sampled_from(views._REVOCATION_RECORD_MEMBERS))
    shape = draw(st.sampled_from(("remove", "retype", "extra")))
    if shape == "remove":
        del mutated[member]
    elif shape == "retype":
        mutated[member] = draw(st.sampled_from(REVOCATION_HOSTILE[member]))
    else:
        mutated[draw(st.sampled_from(("reason", "__proto__", "revoked_by")))] = "x"
    return mutated


@PROPERTY_SETTINGS
@given(hostile_revocation_record(REVOCATION_RECORD))
def test_every_revocation_record_member_is_checked(mutated: dict[str, Any]) -> None:
    assume(_differs(mutated, REVOCATION_RECORD))
    with pytest.raises(views.ViewError):
        views.build_revocation_view([mutated])


# --- hostile subclasses (F8, P32) --------------------------------------------


class HostileDict(dict[Any, Any]):
    """A mapping whose every shadowable accessor either lies or explodes."""

    def __iter__(self) -> Any:
        raise AssertionError("a live view object was iterated instead of copied")

    def keys(self) -> Any:
        raise AssertionError("a live view object's keys() was called")

    def items(self) -> Any:
        raise AssertionError("a live view object's items() was called")

    def values(self) -> Any:
        raise AssertionError("a live view object's values() was called")

    def __getitem__(self, key: Any) -> Any:
        raise AssertionError("a live view object was subscripted")

    def get(self, *args: Any, **kwargs: Any) -> Any:
        raise AssertionError("a live view object's get() was called")

    def __len__(self) -> int:
        return 0

    def __eq__(self, other: object) -> bool:
        return True

    __hash__ = object.__hash__


class HostileList(list[Any]):
    def __iter__(self) -> Any:
        raise AssertionError("a live view array was iterated instead of copied")

    def __getitem__(self, index: Any) -> Any:
        raise AssertionError("a live view array was subscripted")

    def __len__(self) -> int:
        return 0

    def __eq__(self, other: object) -> bool:
        return True

    __hash__ = object.__hash__


class HostileStr(str):
    def __str__(self) -> str:
        return "poisoned"

    def __eq__(self, other: object) -> bool:
        return True

    __hash__ = str.__hash__


class HostileInt(int):
    def __int__(self) -> int:
        return 0

    def __eq__(self, other: object) -> bool:
        return True

    __hash__ = int.__hash__


def _hostile(value: Any) -> Any:
    """The same JSON value, every container and scalar replaced by a subclass
    that shadows what `canon.dumps` would otherwise call."""
    if isinstance(value, bool) or value is None:
        return value
    if isinstance(value, dict):
        return HostileDict({_hostile(k): _hostile(v) for k, v in value.items()})
    if isinstance(value, list):
        return HostileList([_hostile(item) for item in value])
    if isinstance(value, str):
        return HostileStr(value)
    if isinstance(value, int):
        return HostileInt(value)
    return value


def _assert_plain(value: Any, where: str) -> None:
    """Every node is of an EXACT plain type — no subclass survived the copy."""
    assert type(value) in (dict, list, str, int, bool, type(None)), (
        f"{where}: {type(value).__name__} reached canonicalization"
    )
    if type(value) is dict:
        for key, item in value.items():
            _assert_plain(key, where)
            _assert_plain(item, where)
    elif type(value) is list:
        for item in value:
            _assert_plain(item, where)


@pytest.fixture
def plain_only(monkeypatch: pytest.MonkeyPatch) -> None:
    """Fail the test if anything but exact plain types is serialized."""
    real_dumps = canon.dumps
    real_bytes = canon.canonical_bytes

    def guarded_dumps(obj: object) -> str:
        _assert_plain(obj, "canon.dumps")
        return real_dumps(obj)

    def guarded_bytes(obj: object) -> bytes:
        _assert_plain(obj, "canon.canonical_bytes")
        return real_bytes(obj)

    monkeypatch.setattr(canon, "dumps", guarded_dumps)
    monkeypatch.setattr(canon, "canonical_bytes", guarded_bytes)


@pytest.mark.usefixtures("plain_only")
def test_hostile_compromise_claim_produces_the_clean_artifact() -> None:
    built = views.build_compromise_claim(_hostile(MANIFEST), _hostile(EVIDENCE))
    assert canon.canonical_bytes(built) == canon.canonical_bytes(CLAIM)


@pytest.mark.usefixtures("plain_only")
def test_hostile_compromise_view_produces_the_clean_artifact() -> None:
    built = views.build_compromise_view(_hostile([CLAIM]))
    assert canon.canonical_bytes(built) == canon.canonical_bytes([CLAIM])


@pytest.mark.usefixtures("plain_only")
def test_hostile_transfer_claim_produces_the_clean_artifact() -> None:
    built = views.build_transfer_claim(_hostile(TRANSFER_RECORD), _hostile(TRANSFER_EVIDENCE))
    assert canon.canonical_bytes(built) == canon.canonical_bytes(TRANSFER_CLAIM)


@pytest.mark.usefixtures("plain_only")
def test_hostile_revocation_view_produces_the_clean_artifact() -> None:
    built = views.build_revocation_view(_hostile([REVOCATION_RECORD]))
    assert canon.canonical_bytes(built) == canon.canonical_bytes([REVOCATION_RECORD])


@pytest.mark.usefixtures("plain_only")
def test_hostile_trust_material_reaches_the_preflight_not_the_serializer() -> None:
    head = _json(
        VECTORS / "41-compromise-cutoff" / "a-rescued-anchored-before-cutoff" / "manifests.json"
    )["manifests"]["store.example.com"]
    report = views.claim_capabilities(_hostile(CLAIM), _hostile(head), None)
    assert report[MANIFEST["keys"][0]["kid"]]["floor"] == "established"


# --- two-sided boundaries ----------------------------------------------------


def _entry_for(manifest: dict[str, Any]) -> dict[str, Any]:
    """The expected log entry, computed here from `canon` primitives — never
    read back out of the module under test."""
    return {
        "type": "key-manifest",
        "issuer": manifest["issuer"],
        "manifest_version": manifest["manifest_version"],
        "manifest_sha256": hashlib.sha256(canon.canonical_bytes(manifest)).hexdigest(),
    }


def _manifest_with(entry_count: int) -> tuple[dict[str, Any], dict[str, Any]]:
    """A self-consistent manifest carrying exactly `entry_count` keys, one of
    them `compromised`, paired with evidence that commits to it."""
    signer = keys.from_seed(bytes([3]) * 32)
    victim = keys.from_seed(bytes([4]) * 32)
    signer_kid = "shop.example.org/keys/2025-01#ed25519-signer"
    entries = [
        manifests.key_entry(signer_kid, signer.pub, "2025-01-01T00:00:00Z"),
        manifests.key_entry(
            "shop.example.org/keys/2024-01#ed25519-victim",
            victim.pub,
            "2024-01-01T00:00:00Z",
            status="compromised",
        ),
    ]
    entries += [
        manifests.key_entry(
            f"shop.example.org/keys/2025-01#filler-{index}", victim.pub, "2025-01-01T00:00:00Z"
        )
        for index in range(entry_count - len(entries))
    ]
    manifest = manifests.build_key_manifest(
        "shop.example.org", 1, "2025-01-01T00:00:00Z", entries, signer, signer_kid
    )
    evidence = {
        "entry": _entry_for(manifest),
        "leaf_index": 0,
        "tree_size": 1,
        "inclusion_proof": [],
        "checkpoint": "shop.example.org/log\n1\nQUJD\n",
    }
    return manifest, evidence


def test_manifest_key_ceiling_is_two_sided() -> None:
    at_ceiling, evidence = _manifest_with(manifests.MAX_MANIFEST_KEYS)
    assert len(views.build_compromise_claim(at_ceiling, evidence)["manifest"]["keys"]) == (
        manifests.MAX_MANIFEST_KEYS
    )
    over, over_evidence = _manifest_with(manifests.MAX_MANIFEST_KEYS + 1)
    with pytest.raises(views.ViewError, match=str(manifests.MAX_MANIFEST_KEYS)):
        views.build_compromise_claim(over, over_evidence)


def _distinct_claims(count: int) -> list[dict[str, Any]]:
    """`count` claims that differ only in a member no commitment covers, so the
    identical-claim refusal cannot be what a ceiling test measures."""
    claims = []
    for index in range(count):
        claim = copy.deepcopy(CLAIM)
        claim["evidence"]["checkpoint"] = f"{EVIDENCE['checkpoint']}{index}"
        claims.append(claim)
    return claims


def test_compromise_view_ceiling_is_two_sided() -> None:
    ceiling = views._MAX_COMPROMISE_CLAIMS
    assert len(views.build_compromise_view(_distinct_claims(ceiling))) == ceiling
    with pytest.raises(views.ViewError, match=str(ceiling)):
        views.build_compromise_view(_distinct_claims(ceiling + 1))


def _distinct_records(count: int) -> list[dict[str, Any]]:
    records = []
    for index in range(count):
        record = copy.deepcopy(REVOCATION_RECORD)
        record["revoked_at"] = (
            f"2025-08-01T{index // 3600:02d}:{index // 60 % 60:02d}:{index % 60:02d}Z"
        )
        records.append(record)
    return records


def test_revocation_view_ceiling_is_two_sided() -> None:
    ceiling = revocation.MAX_REVOCATION_RECORDS
    assert len(views.build_revocation_view(_distinct_records(ceiling))) == ceiling
    with pytest.raises(views.ViewError, match=str(ceiling)):
        views.build_revocation_view([None] * (ceiling + 1))


def test_transfer_view_ceiling_is_two_sided() -> None:
    ceiling = transfer.MAX_TRANSFER_CLAIMS
    claims = []
    for index in range(ceiling + 1):
        claim = copy.deepcopy(TRANSFER_CLAIM)
        claim["evidence"]["checkpoint"] = f"{TRANSFER_EVIDENCE['checkpoint']}{index}"
        claims.append(claim)
    assert len(views.build_transfer_view(claims[:ceiling])) == ceiling
    with pytest.raises(views.ViewError, match=str(ceiling)):
        views.build_transfer_view(claims)


def _nested(depth: int) -> dict[str, Any]:
    node: dict[str, Any] = {}
    for _ in range(depth - 1):
        node = {"n": node}
    return node


# `canon._serialize` starts the outermost container at depth 1 and refuses a
# container at depth > MAX_DEPTH. `verify._materialize_compromise_view` admits
# each claim at `VIEW_MEMBER_NESTING`, so the containers ABOVE the nested value
# are the claim object and the `evidence` object; the first level of the nested
# chain is `anchors` itself. Deriving this from the position the VERIFIER reads
# is the point: computed from the deeper position instead, the ceiling is one
# level too strict and the producer refuses claims the verifier accepts.
_ANCHOR_DEPTH_CEILING = canon.MAX_DEPTH - canon.VIEW_MEMBER_NESTING - 2


def test_the_claim_depth_ceiling_is_the_one_the_verifier_applies() -> None:
    """The producer must admit exactly what `_materialize_compromise_view`
    admits. A claim at the ceiling is built AND survives the verifier's own
    materializer; one level deeper is refused by both."""
    at_ceiling = copy.deepcopy(EVIDENCE)
    at_ceiling["anchors"] = _nested(_ANCHOR_DEPTH_CEILING)
    claim = views.build_compromise_claim(copy.deepcopy(MANIFEST), at_ceiling)
    assert verify._materialize_compromise_view([claim]) is not None

    over = copy.deepcopy(EVIDENCE)
    over["anchors"] = _nested(_ANCHOR_DEPTH_CEILING + 1)
    with pytest.raises(views.ViewError, match="admissible"):
        views.build_compromise_claim(copy.deepcopy(MANIFEST), over)
    hand_built = {"manifest": copy.deepcopy(MANIFEST), "evidence": over}
    assert verify._materialize_compromise_view([hand_built]) == [None]


def test_claim_depth_ceiling_is_two_sided() -> None:
    at_ceiling = copy.deepcopy(EVIDENCE)
    at_ceiling["anchors"] = _nested(_ANCHOR_DEPTH_CEILING)
    assert views.build_compromise_claim(copy.deepcopy(MANIFEST), at_ceiling)["evidence"]["anchors"]
    over = copy.deepcopy(EVIDENCE)
    over["anchors"] = _nested(_ANCHOR_DEPTH_CEILING + 1)
    with pytest.raises(views.ViewError, match="admissible"):
        views.build_compromise_claim(copy.deepcopy(MANIFEST), over)


# --- the catch-all: only ViewError ever escapes -------------------------------

JSON_VALUES = st.recursive(
    st.none() | st.booleans() | st.integers(-(10**6), 10**6) | st.text(max_size=8),
    lambda children: (
        st.lists(children, max_size=4) | st.dictionaries(st.text(max_size=6), children, max_size=4)
    ),
    max_leaves=12,
)


@PROPERTY_SETTINGS
@given(JSON_VALUES, JSON_VALUES)
def test_only_view_error_escapes_any_builder(first: Any, second: Any) -> None:
    """Arbitrary JSON into every public entry point. A `KeyError`, a
    `TypeError`, a `CanonError` or a `TransparencyError` escaping here would
    make a caller unable to tell "your input is malformed" from "this module
    is broken"."""
    calls = (
        lambda: views.key_manifest_log_entry(first),
        lambda: views.build_compromise_claim(first, second),
        lambda: views.build_compromise_view(first),
        lambda: views.build_transfer_claim(first, second),
        lambda: views.build_transfer_view(first),
        lambda: views.build_revocation_view(first),
        lambda: views.build_revocation_view(first, second),
        lambda: views.claim_capabilities(first, second, None),
        lambda: views.claim_capabilities(first, second, [first]),
    )
    for call in calls:
        try:
            call()
        except views.ViewError:
            pass
