// The shared container corpus, read the same way the Python suite reads it.
//
// One bench, two implementations: `tests/container-corpus/` is generated by
// `tools/gen_container_corpus.py`, which never imports either reader, and both
// suites judge themselves against the same leaves. A disagreement between the
// two readers is a failing test on one side or the other, never a field report
// about two verifiers that read the same file differently.

import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath, URL as NodeURL } from 'node:url'

const HERE = fileURLToPath(new NodeURL('.', import.meta.url))
export const CORPUS_ROOT = join(HERE, '..', '..', '..', 'tests', 'container-corpus')

export interface CorpusCaps {
  max_entries: number
  max_member_bytes: number
  max_total_bytes: number
}

export interface CorpusMember {
  name: string
  method: number
  size: number
  sha256: string
}

export interface CorpusExpectation {
  caps: CorpusCaps
  verdict: 'accept' | 'reject'
  code?: string
  member?: string | null
  members?: CorpusMember[]
}

export const leafNames = (): string[] =>
  readdirSync(CORPUS_ROOT)
    .filter((name) => statSync(join(CORPUS_ROOT, name)).isDirectory())
    .sort()

export const archiveBytes = (leaf: string): Uint8Array =>
  new Uint8Array(readFileSync(join(CORPUS_ROOT, leaf, 'archive.zip')))

export const expectation = (leaf: string): CorpusExpectation =>
  JSON.parse(readFileSync(join(CORPUS_ROOT, leaf, 'expected.json'), 'utf8')) as CorpusExpectation

export const codesTable = (): { codes: string[]; messages: Record<string, string> } =>
  JSON.parse(readFileSync(join(CORPUS_ROOT, 'codes.json'), 'utf8')) as {
    codes: string[]
    messages: Record<string, string>
  }
